---

- name: "Create a VPC named {{ vpc.name }} in {{ vpc.region }} with CIDR block {{ vpc.cidr_block }}"
  ec2_vpc_net:
    name: "{{ vpc.name }}"
    cidr_block: "{{ vpc.cidr_block }}"
    region: "{{ vpc.region }}"
    tags: "{{ vpc.tags | default('') }}"
    state: present
  register: ec2

- name: "Add IGW for VPC {{ vpc.name }}"
  ec2_vpc_igw:
    vpc_id: "{{ ec2.vpc.id }}"
    region: "{{ vpc.region }}"
    tags: "{{ vpc.igw.tags | default('') }}"
    state: present
  register: igw

- name: "Create all subnets for VPC {{ vpc.name }}"
  ec2_vpc_subnet:
    vpc_id: "{{ ec2.vpc.id }}"
    region: "{{ vpc.region }}"
    az: "{{ vpc.region }}{{ item.az }}"
    cidr: "{{ item.cidr }}"
    tags: "{{ item.tags | default({}) }}"
    state: present
  loop: "{{ vpc.subnets }}"
  register: subnets_reply

- name: Grab subnet metadata from results
  set_fact:
    subnets: "{{ subnets_reply.results }}"

- name: Setup subnet ID list
  set_fact:
    subnet_ids: []

- name: Get subnet IDs from results
  set_fact:
    subnet_ids: "{{ subnet_ids + [ item.subnet.id ]}}"
  with_items: "{{ subnets }}"

- debug:
   var: subnet_ids

- name: Create NACLs for subnets
  ec2_vpc_nacl:
    vpc_id: "{{ ec2.vpc.id }}"
    region: "{{ vpc.region }}"
    subnets: "{{ subnet_ids }}"
    name: "{{ item.name }}"
    tags: "{{ item.tags | default({}) }}"
    state: present
  loop: "{{ vpc.nacls }}"

# - name: "Create routing tables for subnets in VPC {{ vpc.name }}"

