---

- name: "Create a VPC named {{ vpc.name }} in {{ vpc.region }} with CIDR block {{ vpc.cidr_block }}"
  ec2_vpc_net:
    name: "{{ vpc.name }}"
    cidr_block: "{{ vpc.cidr_block }}"
    region: "{{ vpc.region }}"
    tags: "{{ vpc.tags | default('') }}"
    state: present
  register: ec2

- name: "Add IGW for VPC {{ vpc.name }}"
  ec2_vpc_igw:
    vpc_id: "{{ ec2.vpc.id }}"
    region: "{{ vpc.region }}"
    tags: "{{ vpc.igw.tags | default('') }}"
    state: present
  register: igw

- name: "Create all subnets for VPC {{ vpc.name }}"
  ec2_vpc_subnet:
    vpc_id: "{{ ec2.vpc.id }}"
    region: "{{ vpc.region }}"
    az: "{{ vpc.region }}{{ item.az }}"
    cidr: "{{ item.cidr }}"
    tags: "{{ item.tags | default({}) }}"
    map_public: "{{ item.public }}"
    state: present
  loop: "{{ vpc.subnets }}"
  register: subnets_reply

- name: Grab subnet metadata from results
  set_fact:
    subnets: "{{ subnets_reply.results }}"

- name: Setup subnet ID list
  set_fact:
    subnet_ids: []

- name: Get subnet IDs from results
  set_fact:
    subnet_ids: "{{ subnet_ids + [ item.subnet.id ]}}"
  with_items: "{{ subnets }}"

- name: Create NACL for public subnets
  ec2_vpc_nacl:
    vpc_id: "{{ ec2.vpc.id }}"
    region: "{{ vpc.region }}"
    subnets:
      - public-a
      - public-b
      - public-c
    name: "{{ vpc.nacls.public.name }}"
    ingress: "{{ vpc.nacls.public.ingress }}"
    egress: "{{ vpc.nacls.public.egress | default([]) }}"
    tags: "{{ vpc.nacls.public.tags | default({}) }}"
    state: present

- name: Create NACL for private subnets
  ec2_vpc_nacl:
    vpc_id: "{{ ec2.vpc.id }}"
    region: "{{ vpc.region }}"
    subnets:
      - private-a
      - private-b
      - private-c
    name: "{{ vpc.nacls.private.name }}"
    ingress: "{{ vpc.nacls.private.ingress }}"
    egress: "{{ vpc.nacls.private.egress | default([]) }}"
    tags: "{{ vpc.nacls.private.tags | default({}) }}"
    state: present

- name: "Create routing tables for public subnets in VPC {{ vpc.name }}"
  ec2_vpc_route_table:
    vpc_id: "{{ ec2.vpc.id }}"
    region: "{{ vpc.region }}"
    tags:
      Name: Public
    subnets:
      - public-a
      - public-b
      - public-c
    routes:
      - dest: 10.1.0.0/16
        gateway_id: local
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"

- name: "Create routing tables for private subnets in VPC {{ vpc.name }}"
  ec2_vpc_route_table:
    vpc_id: "{{ ec2.vpc.id }}"
    region: "{{ vpc.region }}"
    tags:
      Name: Private
    subnets:
      - private-a
      - private-b
      - private-c
    routes:
      - dest: 10.1.0.0/16
        gateway_id: local
