---

#- rds:
#    command: create
#    instance_name: jactest
#    db_engine: postgres
#    size: 1024
#    instance_type: db.t2.micro
#    username: mysql_admin
#    password: 1nsecure
#    tags:
#      Environment: testing
#      Application: cms