---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - include_role:
      name: airflow-aws

- hosts: airflow
  gather_facts: False
  remote_user: ubuntu
  become: yes

  tasks:
  - set_fact:
      ansible_ssh_private_key_file: /Users/jcastellani/.ssh/jachomework.pem
      ansible_python_interpreter: /usr/bin/python3

  - name: Create symlink for /usr/bin/python
    file:
      src: /usr/bin/python3
      dest: /usr/bin/python
      state: link

  - name: Install and configure Airflow
    include_role:
      name: airflow
