---

vpc:
  name: jac-test-vpc
  cidr_block: 10.1.0.0/16
  region: us-east-2
  tags:
    name: jactest

  igw:
    tags:
      name: jac-test-igw

  subnets:
    - name: public
      az: a
      public: true
      cidr: 10.1.1.0/24

    - name: private
      az: a
      public: no
      cidr: 10.1.2.0/24

    - name: public
      az: b
      public: true
      cidr: 10.1.3.0/24

    - name: private
      az: b
      public: no
      cidr: 10.1.4.0/24

    - name: public
      az: c
      public: true
      cidr: 10.1.5.0/24

    - name: private
      az: c
      public: no
      cidr: 10.1.6.0/24

  nacls:
    - name: Allow outbound traffic to anywhere
      egress:
        - [100, 'all', 'allow', '0.0.0.0/0', null, null, null, null]

    - name: Allow SSH from all IPs
      ingress:
        - [100, 'tcp', 'allow', '0.0.0.0/0', null, null, 22, 22]

    - name: Allow inbound on any port from any server in the  VPC
      ingress:
        - [200, 'tcp', 'allow', '10.1.0.0/16', null, null, null, null]

    - name: Deny all other inbound traffic
      ingress:
        - [300, all, 'deny', '0.0.0.0/0', null, null, null, null]
